version: '3.1'
services:
  db:
    image: postgres:14
    restart: always
    #command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend-test:
    build:
      context: backend
      dockerfile: deployment/test/Dockerfile
    environment:
      CONFIG_DATABASE_HOST: db
    depends_on:
      - db

