version: '3.1'
services:
  db:
    image: postgres:14
    restart: always
    #command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend-test:
    build:
      context: backend
      dockerfile: deployment/test/Dockerfile
    environment:
      CONFIG_DATABASE_HOST: db
    depends_on:
      - db
  minio:
    image: bitnami/minio:2022.7.17-debian-11-r1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_DEFAULT_BUCKETS: warehouse-import-files
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-secret
