"""001-first-tables

Revision ID: 8c3ef8cd0141
Revises: 
Create Date: 2022-07-21 01:24:58.498808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c3ef8cd0141"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("art_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("art_id"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "products_articles",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.UniqueConstraint("product_id", "article_id", name="uix_1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products_articles")
    op.drop_table("products")
    op.drop_table("articles")
    # ### end Alembic commands ###
