"""001-init-structure

Revision ID: 7b41b750dd2f
Revises: 
Create Date: 2022-07-23 00:19:43.802343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b41b750dd2f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("article_id"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "products_articles",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.UniqueConstraint("product_id", "article_id", name="uix_1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products_articles")
    op.drop_table("products")
    op.drop_table("articles")
    # ### end Alembic commands ###
