"""001-init-schema

Revision ID: 8bc81ee279a6
Revises: 
Create Date: 2022-07-26 20:21:15.314226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8bc81ee279a6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("article_id"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "products_articles",
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.UniqueConstraint("product_id", "article_id", name="uix_1"),
    )
    op.create_table(
        "sales",
        sa.Column("sale_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.PrimaryKeyConstraint("sale_id"),
    )
    op.create_table(
        "stock_updates",
        sa.Column("update_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column("sale_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.sale_id"],
        ),
        sa.PrimaryKeyConstraint("update_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_updates")
    op.drop_table("sales")
    op.drop_table("products_articles")
    op.drop_table("products")
    op.drop_table("articles")
    # ### end Alembic commands ###
