"""002-sales

Revision ID: 326e119cd3b5
Revises: 7b41b750dd2f
Create Date: 2022-07-24 00:35:01.781234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "326e119cd3b5"
down_revision = "7b41b750dd2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales",
        sa.Column("sale_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.PrimaryKeyConstraint("sale_id"),
    )
    op.create_table(
        "stock_updates",
        sa.Column("update_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("sale_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.sale_id"],
        ),
        sa.PrimaryKeyConstraint("update_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_updates")
    op.drop_table("sales")
    # ### end Alembic commands ###
