name: 'Backend tests'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run database
        run: docker-compose up -d db
      - name: Run tests
        run: docker-compose up --build --exit-code-from backend-test backend-test
