name: 'Run application tests'
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build backend tests
        run: docker compose --profile backend-tests build
      - name: Run backend tests
        run: docker compose --profile backend-tests up --exit-code-from pytest
