name: 'Run application tests'
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build backend tests
        run: docker compose --profile backend-tests build
      - name: Run backend tests
        run: docker compose --profile backend-tests up --exit-code-from pytest
  frontend:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Start Mocked API
        run: docker-compose up -d mock-api
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run tests
        run: npm run test:e2e
        working-directory: ./frontend